export default {
  'Workflows/': {
    name:            'Workflows/',
    dir:             true,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  16,
    _dataBinary:     true,
    options:         {
      compression:        'STORE',
      compressionOptions: null,
    },
  },
  'Workflows/FirstTestFlow-0F48CBA9-EF0C-ED11-82E4-000D3A64F6F2.json': {
    name:            'Workflows/FirstTestFlow-0F48CBA9-EF0C-ED11-82E4-000D3A64F6F2.json',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  32,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    194,
      uncompressedSize:  341,
      crc32:             1060205377,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'Workflows/FirstTestFlow-0F48CBA9-EF0C-ED11-82E4-000D3A64F6F2.json',
  },
  'Workflows/SecondTestFlow-F4910F26-8210-EC11-B6E6-002248842287.json': {
    name:            'Workflows/SecondTestFlow-F4910F26-8210-EC11-B6E6-002248842287.json',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  32,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    202,
      uncompressedSize:  362,
      crc32:             1218257466,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'Workflows/SecondTestFlow-F4910F26-8210-EC11-B6E6-002248842287.json',
  },
  '[Content_Types].xml': {
    name:            '[Content_Types].xml',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    165,
      uncompressedSize:  258,
      crc32:             -219579692,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: '[Content_Types].xml',
  },
  'customizations.xml': {
    name:            'customizations.xml',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    909,
      uncompressedSize:  5827,
      crc32:             2098487185,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'customizations.xml',
  },
  'solution.xml': {
    name:            'solution.xml',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    458,
      uncompressedSize:  1101,
      crc32:             -1087872870,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'solution.xml',
  },
  'Workflows/FirstCopyFlow-01234567-XXXX-YYYY-ZZZZ-987654321098.json': {
    name:            'Workflows/FirstCopyFlow-01234567-XXXX-YYYY-ZZZZ-987654321098.json',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    203,
      uncompressedSize:  362,
      crc32:             1218257466,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'Workflows/FirstCopyFlow-01234567-XXXX-YYYY-ZZZZ-987654321098.json',
  },
  'Workflows/SecondCopyFlow-12345678-YYYY-ZZZZ-XXXX-876543210987.json': {
    name:            'Workflows/SecondCopyFlow-12345678-YYYY-ZZZZ-XXXX-876543210987.json',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    195,
      uncompressedSize:  341,
      crc32:             1060205377,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'Workflows/SecondCopyFlow-12345678-YYYY-ZZZZ-XXXX-876543210987.json',
  },
  'Workflows/ThirdCopyFlow-23456789-ZZZZ-XXXX-YYYY-765432109876.json': {
    name:            'Workflows/ThirdCopyFlow-23456789-ZZZZ-XXXX-YYYY-765432109876.json',
    dir:             false,
    comment:         null,
    unixPermissions: null,
    dosPermissions:  0,
    date:            expect.any(Date),
    _data:           {
      compressedContent: expect.any(Uint8Array),
      compressedSize:    195,
      uncompressedSize:  341,
      crc32:             1060205377,
      compression:       {
        magic: expect.any(String),
      },
    },
    _dataBinary: true,
    options:     {
      compression:        null,
      compressionOptions: null,
    },
    unsafeOriginalName: 'Workflows/ThirdCopyFlow-23456789-ZZZZ-XXXX-YYYY-765432109876.json',
  },
}
