name: Build & publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1
      with:
        file-url: https://raw.githubusercontent.com/russoedu/SoFloC-service/main/package.json
        static-checking: localIsNew

    - name: Log when changed
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

    - name: Log when unchanged
      if: steps.check.outputs.changed == 'false'
      run: 'echo "No version change :/"'

    - name: Install Node.js
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install NPM packages
      if: steps.check.outputs.changed == 'true'
      run: npm install

    - name: Build app
      if: steps.check.outputs.changed == 'true'
      run: npm run build

    - name: Publish
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

